---
- name: Starting a Microk8s Cluster with storage volume
  hosts: localhost
  vars_prompt:
  - name: application_credential_ID
    prompt: "Enter the Application Credential ID from Nimbus dashboard"
    private: no
  - name: application_credential_secret
    prompt: "Enter the Application Credential secret from Nimbus dashboard"
    private: no
  - name: storage_vol_size
    prompt: "Enter the size of your data storage volume in gigabytes"
    private: no
  tasks:
  - name: Install MicrokK8s
    script:
      cmd: /home/ubuntu/ansible_scripts/install_microk8s.sh
  - name: Set up Openstack cloud provider
    script:
      cmd: /home/ubuntu/ansible_scripts/add_cloud_provider.sh '{{ application_credential_ID }}' '{{ application_credential_secret }}'
  - name: Create Storage Class
    script:
      cmd: /home/ubuntu/ansible_scripts/add_storage_class.sh
  - name: Create Persistent Volume Claim
    script: 
      cmd: /home/ubuntu/ansible_scripts/add_storage.sh '{{ storage_vol_size }}'
  - name: Mount data volume
    script:
      cmd: /home/ubuntu/ansible_scripts/mount_data.sh
