---
- name: Add a Miniconda3 application to existing Microk8s cluster
  hosts: localhost
  vars_prompt:
  - name: pubkey_path
    prompt: "Enter the path to your ssh private key on your local machine"
    private: no
  tasks:
  # - name: Add a Miniconda3 application
  #   shell:
  #     cmd: microk8s kubectl apply -f /home/ubuntu/miniconda3-deployment.yaml && microk8s kubectl expose deployment miniconda3-deployment --target-port=8888 --name=conda-jupyternotebook --type=NodePort
  #     creates: conda-jupyternotebook
  #   become: yes
  - name: Run instructions script
    script: /home/ubuntu/ansible_scripts/add_miniconda3_app.sh '{{ pubkey_path }}'
    become: yes
    register: result
  - name: Print Jupyter Notebook instructions
    debug: 
      var: result.stdout_lines