---
- name: Starting a Microk8s Cluster with storage volume
  hosts: localhost
  vars_prompt:
  - name: storage_vol_name
    prompt: "Enter a name for your data storage volume"
    private: no
  - name: storage_vol_size
    prompt: "Enter the size of your data storage volume in gigabytes"
    private: no
  tasks:
  - name: Install MicrokK8s
    script:
      cmd: /home/ubuntu/ansible_scripts/install_microk8s.sh
  - name: Add Storage
    script: 
      cmd: /home/ubuntu/ansible_scripts/add_storage.sh '{{ storage_vol_name }}' '{{ storage_vol_size }}'
