---
- name: Add an RStudio application to existing Microk8s cluster
  hosts: localhost
  vars_prompt:
  - name: R_version
    prompt: "Enter the R version you require (supported versions are 3.6.3 and >= 4.0.0) - ensure it is available as a tag at https://hub.docker.com/r/rocker/rstudio/tags"
    private: no  
  - name: rstudio_password
    prompt: "Enter a new password for RStudio"
    private: no
  - name: pubkey_path
    prompt: "Enter the path to your ssh private key on your local machine, e.g. ~/.ssh/id_rsa.key"
    private: no
  tasks:
  - name: Create RStudio server folder
    command: mkdir -p /tmp/rstudio-server
    args:  
      creates: /tmp/rstudio-server
      warn: false
  - name: Create a data folder
    command: mkdir /data
    become: yes
    args:
      creates: /data
  - name: Change ownership of data folder
    command: chown ubuntu:ubuntu /data
    become: yes
    args:
      warn: false
  - name: Delete any existing RStudio deployment
    command: microk8s kubectl delete deployment.apps/rstudio-deployment service/rstudio-server
    become: yes
    ignore_errors: yes
  - name: Add an RStudio application
    shell:
      cmd: cp /home/ubuntu/microk8s-on-nimbus/rstudio-deployment.yaml /home/ubuntu/microk8s-on-nimbus/rstudio-deployment-{{ R_version }}.yaml && 
           sed -i 's/R_version/{{ R_version }}/g' /home/ubuntu/microk8s-on-nimbus/rstudio-deployment-{{ R_version }}.yaml &&
           sed -i 's/rstudio_password/{{ rstudio_password }}/g' /home/ubuntu/microk8s-on-nimbus/rstudio-deployment-{{ R_version }}.yaml && 
           microk8s kubectl apply -f /home/ubuntu/microk8s-on-nimbus/rstudio-deployment-{{ R_version }}.yaml && 
           microk8s kubectl expose deployment rstudio-deployment --target-port=8787 --name=rstudio-server --type=NodePort
      creates: "{{ container_name }}-server"
      warn: false
    become: yes
  - name: Wait for Kubernetes to deploy service
    wait_for:
      timeout: 60
  - name: Run instructions script
    script: /home/ubuntu/microk8s-on-nimbus/ansible_scripts/add_rstudio_app.sh '{{ pubkey_path }}' '{{ rstudio_password}}'
    become: yes
    register: result_rstudio
  - name: Mount data volume
    command: mount /dev/vdc /data
    ignore_errors: yes    
    become: yes 
  - name: Print RStudio server instructions
    debug: 
      var: result_rstudio.stdout_lines