apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniconda3-deployment
  labels:
    app: miniconda3
spec:
  selector:
    matchLabels:
      app: miniconda3
  template:
    metadata:
      labels:
        app: miniconda3
    spec:
      containers:
      - name: miniconda3
        image: continuumio/miniconda3:4.9.2
        env:
        - name: JUPYTERCMD
          value: "conda install jupyter -y --quiet && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
        command: ["bash"]
        args: ["-c", "$(JUPYTERCMD)"]
        ports:
        - containerPort: 8888
        volumeMounts:
        - mountPath: '/opt/notebooks/'
          name: miniconda3-data
      volumes:
      - name: miniconda3-data
        persistentVolumeClaim:
          claimName: data-pvc