apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio-deployment
  labels:
    app: rstudio
spec:
  selector:
    matchLabels:
      app: rstudio
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
      - name: rstudio
        image: localhost:32000/rstudio-container
        env:
        - name: PASSWORD
          value: "abc"
        ports:
        - containerPort: 8787
        volumeMounts:
        - mountPath: '/home'
          name: rstudio-data
        - mountPath: '/var/lib/rstudio-server'
          name: tmp-rstudio-server
        - mountPath: '/var/run/rstudio-server'
          name: tmp-rstudio-server
      volumes:
      - name: rstudio-data
        persistentVolumeClaim:
          claimName: data-pvc
      - name: tmp-rstudio-server
        hostPath:
          path: /tmp/rstudio-server
          type: Directory