apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio-deployment
  labels:
    app: rstudio
spec:
  selector:
    matchLabels:
      app: rstudio
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
      - name: rstudio
        image: rocker/tidyverse:4.0.3
        ports:
        - containerPort: 8787
        volumeMounts:
        - mountPath: '/home/rstudio/'
          name: rstudio-data
      volumes:
      - name: rstudio-data
        persistentVolumeClaim:
          claimName: storage2